#Configure log for firewall
- name: Create firewall file for rsyslog
  template:
    src: rsyslog.j2
    dest: "{{ rsyslog_config_fw_dest }}"

- name: Create logrotate file for firewall log
  template:
    src: logrotate.j2
    dest: "{{ logrotate_config_fw_dest }}"

- name: Reload iptables service
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: Configure sysctl.conf to ensure firewall no logging to stdin
  blockinfile:
    path: /etc/sysctl.conf
    block: "kernel.printk = 3 4 1 7"
