---
# Role configure tasks

- block:
    - name: Create iptables configuration file
      template:
        src: config.j2
        dest: "{{ iptables_config_path }}"
        mode: 0640
      notify:
        - reload iptables service

    - name: Create iptables rules file
      template:
        src: rules.j2
        dest: "{{ iptables_rules_path }}"
        mode: 0640
      notify:
        - restore iptables rules
        - save iptables rules
        - reload iptables service

    - name: Create rsyslog configuration file
      template:
        src: rsyslog.j2
        dest: "{{ iptables_rsyslog_config_path }}"
        mode: 0640
      notify:
        - reload rsyslog service

    - name: Setup log file
      file:
        path: "{{ iptables_log_path }}"
        state: touch
        mode: u+rw,g+r
        modification_time: preserve
        access_time: preserve

    - name: Create logrotate configuration file
      template:
        src: logrotate.j2
        dest: "{{ iptables_logrotate_config_path }}"
        mode: 0640
  vars:
    iptables_zones_managed: >-
      {{ iptables_zones
         + ((iptables_load_zones_from_hostvars)
            | ternary(iptables_hostvars_zones
                      | default([])
                      | flatten,
                      [])) }}

    iptables_services_managed: >-
      {{ iptables_services
         + ((iptables_load_services_from_hostvars)
            | ternary(iptables_hostvars_services
                      | default([])
                      | flatten,
                      [])) }}

    iptables_config_modules_managed: >-
      {{ iptables_config_modules
         + ((iptables_load_config_modules_from_hostvars)
            | ternary(iptables_hostvars_config_modules
                      | default([])
                      | flatten,
                      [])) }}

    iptables_default_policies_raw_rules_managed: >-
      {{ iptables_default_policies_raw_rules
         + ((iptables_load_policies_raw_rules_from_hostvars)
            | ternary(iptables_hostvars_policies_raw_rules
                      | default([])
                      | flatten,
                      [])) }}

    iptables_input_raw_rules_managed: >-
      {{ iptables_input_raw_rules
         + ((iptables_load_input_raw_rules_from_hostvars)
            | ternary(iptables_hostvars_input_raw_rules
                      | default([])
                      | flatten,
                      [])) }}

    iptables_input_log_raw_rules_managed: >-
      {{ iptables_input_log_raw_rules
         + ((iptables_load_input_log_raw_rules_from_hostvars)
            | ternary(iptables_hostvars_input_log_raw_rules
                      | default([])
                      | flatten,
                      [])) }}

    iptables_output_raw_rules_managed: >-
      {{ iptables_output_raw_rules
         + ((iptables_load_output_raw_rules_from_hostvars)
            | ternary(iptables_hostvars_output_raw_rules
                      | default([])
                      | flatten,
                      [])) }}

    iptables_zones_raw_rules_managed: >-
      {{ iptables_zones_raw_rules
         + ((iptables_load_zones_raw_rules_from_hostvars)
            | ternary(iptables_hostvars_zones_raw_rules
                      | default([])
                      | flatten,
                      [])) }}
  tags:
    - role::iptables
    - role::iptables::configure
