---
# Role configure tasks

- block:
    - name: Setup facts items that will be managed
      set_fact:
        iptables_zones_managed: >-
          {{ (iptables_load_zones_from_hostvars
              and not iptables_hostvars_zones is string)
              | ternary([ iptables_hostvars_zones ] | flatten
                        + iptables_zones,
                        iptables_zones) }}

        iptables_services_managed: >-
          {{ (iptables_load_services_from_hostvars
              and not iptables_hostvars_services is string)
              | ternary([ iptables_hostvars_services ] | flatten
                        + iptables_services,
                        iptables_services) }}
        iptables_config_modules_managed: >-
          {{ (iptables_load_config_modules_from_hostvars
              and not iptables_hostvars_config_modules is string)
              | ternary([ iptables_hostvars_config_modules ] | flatten
                        + iptables_config_modules,
                        iptables_hostvars_config_modules) }}

        iptables_default_policies_raw_rules_managed: >-
          {{ (iptables_load_policies_raw_rules_from_hostvars
              and not iptables_hostvars_policies_raw_rules is string)
              | ternary([ iptables_hostvars_policies_raw_rules ] | flatten
                        + iptables_default_policies_raw_rules,
                        iptables_default_policies_raw_rules) }}

        iptables_input_raw_rules_managed: >-
          {{ (iptables_load_input_raw_rules_from_hostvars
              and not iptables_hostvars_input_raw_rules is string)
              | ternary([ iptables_hostvars_input_raw_rules ] | flatten
                        + iptables_input_raw_rules,
                        iptables_input_raw_rules) }}

        iptables_input_log_raw_rules_managed: >-
          {{ (iptables_load_input_log_raw_rules_from_hostvars
              and not iptables_hostvars_input_log_raw_rules is string)
              | ternary([ iptables_hostvars_input_log_raw_rules ] | flatten
                        + iptables_input_log_raw_rules,
                        iptables_input_log_raw_rules) }}

        iptables_output_raw_rules_managed: >-
          {{ (iptables_load_output_raw_rules_from_hostvars
              and not iptables_hostvars_output_raw_rules is string)
              | ternary([ iptables_hostvars_output_raw_rules ] | flatten
                        + iptables_output_raw_rules,
                        iptables_output_raw_rules) }}

        iptables_zones_raw_rules_managed: >-
          {{ (iptables_load_zones_raw_rules_from_hostvars
              and not iptables_hostvars_output_raw_rules is string)
              | ternary([ iptables_hostvars_zones_raw_rules ] | flatten
                        + iptables_zones_raw_rules,
                        iptables_zones_raw_rules) }}

    - name: Create iptables configuration file
      template:
        src: config.j2
        dest: "{{ iptables_config_path }}"
      notify:
        - reload iptables service

    - name: Create iptables rules file
      template:
        src: rules.j2
        dest: "{{ iptables_rules_path }}"
      notify:
        - restore iptables rules
        - save iptables rules
        - reload iptables service

    - name: Create rsyslog configuration file
      template:
        src: rsyslog.j2
        dest: "{{ iptables_rsyslog_config_path }}"
      notify:
        - reload rsyslog service

    - name: Create logrotate configuration file
      template:
        src: logrotate.j2
        dest: "{{ iptables_logrotate_config_path }}"
  tags:
    - role::iptables
    - role::iptables::configure
