# Create configuration files
- name: Create iptables-config file
  template:
    src: iptables-config_template.j2
    dest: "{{ iptables_config_dest }}"
  notify:
    - iptables Service reload

- name: Create iptables-rules file
  template:
    src: iptables-rules_template.j2
    dest: "{{ iptables_rules_dest }}"
  notify:
    - iptables Restore rules from template file
    - iptables Save rules
    - iptables Service reload
