---
# Role install tasks

- block:
    - name: remove obsolete operating system packages
      package:
        name: "{{ item }}"
        state: absent
      loop: "{{ iptables_obsolete_os_packages[distro_packages_key] }}"

    - name: install required operating system packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ iptables_os_packages[distro_packages_key] }}"
  environment: "{{ proxy_client_environment }}"
  vars:
    distro_packages_key: >-
      {{ ansible_facts.distribution
         | lower
         + "_" + ansible_facts.distribution_major_version }}
  tags:
    - role::iptables
    - role::iptables::install
