

# Install required packages
# RedHat:
#   -iptables
#   -iptables-ipv6
# CentOs:
#   -iptables
# Both RedHat and CentOS if version >= 7 (sytemd based OS)
#   -iptables-services

name: install iptables package
package:
  name: iptables
  state: present

name: install iptables-ipv6 package for RedHat
package:
  name: iptables-ipv6
  state: present
when: ansible_distribution == "RedHat"

name: install iptables-services package for sytemd based OS
package:
  name: iptables-services
  state: present
when:
    - ansible_distribution in ["RedHat", "CentOS"]
    - ansible_distribution_version | version_compare('7', '>=')

- name: Enable iptables service
  sudo: yes
  service:
    name=iptables
    enabled=yes
    state=started
