---
# Role tasks
- name: install iptables packages
  include_tasks: install.yml

- name: create configuartion files for rules
  include_tasks: configure.yml

- name: setup iptables service
  include_tasks: service.yml

- name: configure logs for firewall
  include_tasks: configlog.yml
