---
# Role tasks

- block:
    - import_tasks: check.yml
    - import_tasks: install.yml
    - import_tasks: configure.yml
    - import_tasks: service.yml
    - import_tasks: cleanup.yml
  tags:
    - role::iptables
