---
# Role tasks

- block:
    - include_tasks: configure.yml
      tags:
        - role::iptables
        - role::iptables::configure

    - include_tasks: service.yml
      tags:
        - role::iptables
        - role::iptables::service

    - include_tasks: cleanup.yml
      tags:
        - role::iptables
        - role::iptables::cleanup
  tags:
    - role::iptables
