---
# Role handlers

- name: Iptables restore rules
  command: iptables-restore {{ iptables_rules_path }}
  listen: restore iptables rules

- name: Iptables save rules
  shell: iptables-save > {{ iptables_save_path }}
  args:
    warn: no
  listen: save iptables rules

- name: Iptables reload service
  service:
    name: iptables
    state: restarted
    enabled: yes
  listen: reload iptables service

- name: Iptables reload rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes
  listen: reload rsyslog service
