---
# Role handlers

- name: iptables restore rules
  shell: iptables-restore {{ iptables_rules_path }}
  listen: restore iptables rules

- name: iptables save rules
  shell: iptables-save > {{ iptables_rules_path }}
  listen: save iptables rules

- name: iptables reload service
  service:
    name: iptables
    state: reloaded
    enabled: yes
  listen: reload iptables service

- name: iptables reload rsyslog
  service:
    name: rsyslog
    state: reloaded
    enabled: yes
  listen: reload rsyslog service
