---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  export ANSIBLE_ACTION_PLUGINS=$PWD/action_plugins
  export ANSIBLE_BECOME_PLUGINS=$PWD/become_plugins
  export ANSIBLE_CACHE_PLUGINS=$PWD/cache_plugins
  export ANSIBLE_CALLBACK_PLUGINS=$PWD/callback_plugins
  export ANSIBLE_CLICONF_PLUGINS=$PWD/cliconf_plugins
  export ANSIBLE_CONNECTION_PLUGINS=$PWD/connection_plugins
  export ANSIBLE_DOC_FRAGMENT_PLUGINS=$PWD/doc_fragment_plugins
  export ANSIBLE_FILTER_PLUGINS=$PWD/filter_plugins
  export ANSIBLE_HTTPAPI_PLUGINS=$PWD/httpapi_plugins
  export ANSIBLE_INVENTORY_PLUGINS=$PWD/inventory_plugins
  export ANSIBLE_LIBRARY=$PWD/library
  export ANSIBLE_LOOKUP_PLUGINS=$PWD/lookup_plugins
  export ANSIBLE_NETCONF_PLUGINS=$PWD/netconf_plugins
  export ANSIBLE_STRATEGY_PLUGINS=$PWD/strategy_plugins
  export ANSIBLE_TERMINAL_PLUGINS=$PWD/terminal_plugins
  export ANSIBLE_TEST_PLUGINS=$PWD/test_plugins
  export ANSIBLE_VARS_PLUGINS=$PWD/vars_plugins
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    box: centos/6
    memory: 1024
    interfaces:
      - network_name: private_network
        ip: 192.168.50.4
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    interfaces:
      - network_name: private_network
        ip: 192.168.50.5
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora29-${INSTANCE_UUID:-1}"
    box: fedora/29-cloud-base
    memory: 1024
    interfaces:
      - network_name: private_network
        ip: 192.168.50.6
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_29
  - name: "fedora30-${INSTANCE_UUID:-1}"
    box: fedora/30-cloud-base
    memory: 1024
    interfaces:
      - network_name: private_network
        ip: 192.168.50.7
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_30
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          iptables_zones_SERVICE:
            name: SERVICE
            interfaces: eth0
            log: yes
            raw_rules:
              - "-m pkttype --pkt-type multicast -j ACCEPT"
          iptables_zones_MANAGEMENT:
            name: MANAGEMENT
            interfaces: eth0
            log: yes
            raw_rules:
              - "-m pkttype --pkt-type multicast -j REJECT"
          iptables_services_ssh:
            name: ssh
            ports: 22
            zones:
              - SERVICE
              - MANAGEMENT
          iptables_services:
            - name: http
              protocol: tcp
              ports:
                - 80
                - 8080
              zones:
                - SERVICE
            - name: dns
              protocol: udp
              ports: 53
              zones: SERVICE
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
