---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    box: centos/6
    memory: 1024
    interfaces:
      - network_name: private_network
        type: dhcp
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_6
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    memory: 1024
    interfaces:
      - network_name: private_network
        type: dhcp
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "fedora34-${INSTANCE_UUID:-1}"
    box: fedora/34-cloud-base
    memory: 1024
    interfaces:
      - network_name: private_network
        type: dhcp
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    box: fedora/35-cloud-base
    memory: 1024
    interfaces:
      - network_name: private_network
        type: dhcp
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          iptables_zones_SERVICE:
            name: SERVICE
            interfaces: eth0
            log: yes
            raw_rules:
              - "-m pkttype --pkt-type multicast -j ACCEPT"
          iptables_zones_MANAGEMENT:
            name: MANAGEMENT
            interfaces: eth0
            log: yes
            raw_rules:
              - "-m pkttype --pkt-type multicast -j REJECT"
          iptables_services_ssh:
            name: ssh
            comment: "secure shell port"
            ports: 22
            zones:
              - SERVICE
              - MANAGEMENT
          iptables_services:
            - name: http
              protocol: tcp
              ports:
                - 80
                - 8080
              zones:
                - SERVICE
            - name: dns
              protocol: udp
              ports: 53
              zones: SERVICE
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
